### PR TITLE
Add django-csp to project.

### LINKED ISSUE #10: Improvement: Use CSP
There's even a django module for that, django-csp. Also, we will make this a requirement for all future mozilla web properties quite soon. So why not start learning :)

### PR DESCRIPTION
**Pull request by akatsoulas**
Fixes #10

### CODE REVIEW

**Comment by johngian** [comment]
Please rebase.

**Comment by johngian** [comment]
We are fetching images from mozillians.org directly. Please add a CSP rule for that.

**Comment by akatsoulas** [comment]
@johngian pr updated

**Comment by johngian** [comment]
r+

**Pull request merged**
